import { Player } from "../types";

export const players: Player[] = [
  {
    id: 1,
    first_name: 'John',
    last_name: 'Doe',
    date_of_birth: '1990-01-01',
    position: 'Forward',
    category: 'U9',
    status: 'active',
    photo: '',
    birth_certificate_no: '1234567890',
    birth_certificate_file: '',
    country_of_residence: 'Kenya',
    city_of_residence: 'Nairobi',
    height: 180,
    weight: 70,
  },
  {
    id: 2,
    first_name: 'Jane',
    last_name: 'Smith',
    date_of_birth: '1992-02-01',
    position: 'Forward',
    category: 'U9',
    status: 'active',
    photo: '',
    birth_certificate_no: '1234567890',
    birth_certificate_file: '',
    country_of_residence: 'Kenya',
    city_of_residence: 'Nairobi',
    height: 180,
    weight: 70,
  },
  {
    id: 3,
    first_name: 'John',
    last_name: 'Doe',
    date_of_birth: '1990-01-01',
    position: 'Forward',
    category: 'U9',
    status: 'active',
    photo: '',
    birth_certificate_no: '1234567890',
    birth_certificate_file: '',
    country_of_residence: 'Kenya',
  },
  {
    id: 4,
    first_name: 'John',
    last_name: 'Doe',
    date_of_birth: '1990-01-01',
    position: 'Forward',
    category: 'U9',
    status: 'active',
    photo: '',
    birth_certificate_no: '1234567890',
    birth_certificate_file: '',
    country_of_residence: 'Kenya',
    city_of_residence: 'Nairobi',
  },
  {
    id: 5,
    first_name: 'John',
    last_name: 'Doe',
    date_of_birth: '1990-01-01',
    position: 'Forward',
    category: 'U9',
    status: 'active',
    photo: '',
    birth_certificate_no: '1234567890',
    birth_certificate_file: '',
    country_of_residence: 'Kenya',
    city_of_residence: 'Nairobi',
    height: 180,
    weight: 70,
  },
  {
    id: 6,
    first_name: 'Jane',
    last_name: 'Smith',
    date_of_birth: '1992-02-01',
    position: 'Forward',
    category: 'U9',
    status: 'active',
    photo: '',
    birth_certificate_no: '1234567890',
    birth_certificate_file: '',
    country_of_residence: 'Kenya',
    city_of_residence: 'Nairobi',
    height: 180,
    weight: 70,
  },
  {
    id: 7,
    first_name: 'John',
    last_name: 'Doe',
    date_of_birth: '1990-01-01',
    position: 'Forward',
    category: 'U9',
    status: 'active',
    photo: '',
    birth_certificate_no: '1234567890',
    birth_certificate_file: '',
    country_of_residence: 'Kenya',
  },
  {
    id: 8,
    first_name: 'John',
    last_name: 'Doe',
    date_of_birth: '1990-01-01',
    position: 'Forward',
    category: 'U9',
    status: 'active',
    photo: '',
    birth_certificate_no: '1234567890',
    birth_certificate_file: '',
    country_of_residence: 'Kenya',
    city_of_residence: 'Nairobi',
  },
  {
    id: 9,
    first_name: 'John',
    last_name: 'Doe',
    date_of_birth: '1990-01-01',
    position: 'Forward',
    category: 'U9',
    status: 'active',
    photo: '',
    birth_certificate_no: '1234567890',
    birth_certificate_file: '',
    country_of_residence: 'Kenya',
    city_of_residence: 'Nairobi',
    height: 180,
    weight: 70,
  },
  {
    id: 10,
    first_name: 'Jane',
    last_name: 'Smith',
    date_of_birth: '1992-02-01',
    position: 'Forward',
    category: 'U9',
    status: 'active',
    photo: '',
    birth_certificate_no: '1234567890',
    birth_certificate_file: '',
    country_of_residence: 'Kenya',
    city_of_residence: 'Nairobi',
    height: 180,
    weight: 70,
  },
  {
    id: 11,
    first_name: 'John',
    last_name: 'Doe',
    date_of_birth: '1990-01-01',
    position: 'Forward',
    category: 'U9',
    status: 'active',
    photo: '',
    birth_certificate_no: '1234567890',
    birth_certificate_file: '',
    country_of_residence: 'Kenya',
  },
  {
    id: 12,
    first_name: 'John',
    last_name: 'Doe',
    date_of_birth: '1990-01-01',
    position: 'Forward',
    category: 'U9',
    status: 'active',
    photo: '',
    birth_certificate_no: '1234567890',
    birth_certificate_file: '',
    country_of_residence: 'Kenya',
    city_of_residence: 'Nairobi',
  }
];

