import { Tournament } from "../types";

export const tournaments: Tournament[] = [
    {
      id: 1,
      tournament_name: 'East Africa Youth Cup 2024',
      status: 'upcoming',
      start_date: '2024-03-15',
      type_of_sport: 'football',
      total_teams_count: 16,
      organizer_name: 'East Africa Youth Cup',
      organizer_email: 'east.africa.youth.cup@gmail.com',
      organizer_phone: '+254712345678',
      registration_deadline: '2024-03-15',
      end_date: '2024-03-15',
      type_of_tournament: 'league',
      type_of_participation: 'mixed',
      logo: null,
      city: 'Nairobi',
      country: 'Kenya',
      description: 'East Africa Youth Cup 2024',
      max_teams_per_club: 1,
      categories: [],
      teams: [],
    },
    {
        id: 2,
        tournament_name: 'Rausha Kipaji 2025',
        status: 'upcoming',
        start_date: '2025-03-15',
        type_of_sport: 'football',
        total_teams_count: 16,
        organizer_name: 'Rausha Kipaji',
        organizer_email: 'raushakipaji@gmail.com',
        organizer_phone: '+254712345678',
        registration_deadline: '2025-03-15',
        end_date: '2025-03-15',
        type_of_tournament: 'league',
        type_of_participation: 'mixed',
        logo: null,
        city: 'Nairobi',
        country: 'Kenya',
        description: 'Rausha Kipaji 2025',
        max_teams_per_club: 1,
        categories: [],
        teams: [],
    }
  ];